Esp32WifiManager: examples/APModeExample/APModeExample.ino File Reference
APModeExample.ino File Reference
#include <Preferences.h>
#include <WiFi.h>
#include <Esp32WifiManager.h>
Functions
void setup ()
void loop ()
Variables
WifiManager manager
Function Documentation
loop()
void loop ()
Definition at line 11 of file APModeExample.ino.
References Connected, WifiManager::getState(), and WifiManager::loop().
setup()
void setup ()
Definition at line 7 of file APModeExample.ino.
References WifiManager::setupAP().
Variable Documentation
manager
WifiManager manager
Definition at line 6 of file APModeExample.ino.