/*

 Simple web configuration portal

 When it is connected to a WiFi network, everything is fine
 When connection fails, it create a portal to insert a new SSID and password,
 If the new credentials works, it will be stored in ESP32 non volatile storage (NVS).

 In a nutshell: it's a https://github.com/tzapu/WiFiManager for ESP32 with a non blocking implementation and simple design.

 Connect to wifi network generated by ESP32 and tip in your browser:
 AP IPv4: 192.168.4.1  or  AP IPv6

 by Evandro Luis Copercini - 2017
 Public Domain
 */

/*
 TODO: integrate with https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/examples/WiFiScan/WiFiScan.ino
 */

#include "WiFi.h"
#include <Preferences.h>
#include <EspWii.h>

#define AP_SSID  "RBE_Team_1"       //can set ap hostname here
#define AP_PW	 "thisissecret"       //can set ap hostname here



void setup() {

}

void loop() {

}
